version: '3.1'
services:
  stats-server:
    build: ./ewm-stats/ewm-stats-service
    image: ewm-stats-service
    container_name: ewm-stats-service
    ports:
      - "9090:9090"
    environment:
      STATS_SERVER_URL: http://stats-server:9090
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_HOST: stats-db
      SPRING_DATASOURCE_PORT: 5432
      SPRING_DATASOURCE_NAME: stats

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  ewm-service:
    build: ./ewm-main-service
    image: ewm-main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
